baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

paginate = 6

[params]
    description = "The fastest blog"
    dateFormat = "Jan 02, 2006"

[taxonomies]
    category = "categories"
    author = "authors"